<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly.
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5b6f37b5ce5a8',
		'title' => 'Freemius Products',
		'fields' => array(
			array(
				'key' => 'field_5b6f37d6a041e',
				'label' => 'Plugin ID',
				'name' => 'freemius_checkout_public_id',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b6f3803a041f',
				'label' => 'Public Key',
				'name' => 'freemius_checkout_public_key',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b70384138e1b',
				'label' => 'Plans',
				'name' => 'freemius_checkout_plans',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'5b7038b8eb6d8' => array(
						'key' => '5b7038b8eb6d8',
						'name' => 'freemius_checkout_add_new_plans',
						'label' => 'Add new Plan',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b7038c26f92e',
								'label' => 'Plans ID',
								'name' => 'freemius_checkout_plan_id',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5b6f3852c0607',
								'label' => 'Pricing',
								'name' => 'freemius_checkout_pricing',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_5b6f3891c0609',
										'label' => 'Name',
										'name' => 'freemius_checkout_name',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5b6f386bc0608',
										'label' => 'Pricing ID',
										'name' => 'freemius_checkout_pricing_id',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5b6f38a8c060a',
										'label' => 'Monthly Price',
										'name' => 'freemius_checkout_monthly_price',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '$',
										'min' => 0,
										'max' => '',
										'step' => '',
									),
									array(
										'key' => 'field_5b6f38fac060c',
										'label' => 'Annual Price',
										'name' => 'freemius_checkout_annual_price',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '$',
										'min' => 0,
										'max' => '',
										'step' => '',
									),
									array(
										'key' => 'field_5b6f38f8c060b',
										'label' => 'Lifetime Price',
										'name' => 'freemius_checkout_lifetime_price',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '$',
										'min' => 0,
										'max' => '',
										'step' => '',
									),
									array(
										'key' => 'field_5b6f396cc060d',
										'label' => 'Trial',
										'name' => 'freemius_checkout_trial',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'none' => 'None',
											7 => '7 days',
											14 => '14 days',
											30 => '30 days',
										),
										'default_value' => array(
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'return_format' => 'value',
										'ajax' => 0,
										'placeholder' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Ajouter un élément',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'freemius-cpt',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;